import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import EnterPage from "../pages/enter";
import Loader from "../components/Loader";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Home: NextPage = () => {
	const notify = () => toast("Hello Toast!");

	return (
		<div className="">
			<Head>
				<title>next-fire</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Loader show />
			<EnterPage />
			<button onClick={notify}>Toast</button>
			<ToastContainer />

			<Link
				href={{
					pathname: "/[username]",
					query: { username: "Michael" },
				}}>
				<button>Michael's Profile</button>
			</Link>

			<footer className="">
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"></a>
			</footer>
		</div>
	);
};

export default Home;
